# AI Multi-Person Pose Estimation System Configuration File
# This file contains configuration parameters for all services, can be modified as needed

# Global configuration
global:
  # Computing device: cuda or cpu
  devices: "cuda"
  # Log level: DEBUG, INFO, WARN, ERROR
  log_level: "INFO"
  # Startup delay between services (seconds)
  startup_delay: 5
  # Number of worker processes per device
  num_workers_per_device: 1
  # Inference backend: onnxruntime, openvino, tensorrt
  backend: "onnxruntime"

# RTSP stream configuration
rtsp:
  # Input stream address (Docker services use internal network)
  input_stream: "rtsp://localhost:8554"
  input_topic: "mystream"
  # Output stream address
  output_stream: "rtsp://localhost:8554"
  output_topic: "outstream"
  # Output video parameters
  output_width: 1920
  output_height: 1080
  output_fps: 25

# MQTT message queue configuration
mqtt:
  # MQTT server address (Docker services use internal network)
  broker_host: "localhost"
  broker_port: 1883
  # Quality of Service level
  qos: 2
  # Topic configuration
  topics:
    yolox_output: "yolox"
    rtmpose_output: "rtmpose"
    bytetrack_output: "bytetrack"
  # Queue length limits
  queue_limits:
    yolox_output: 50
    rtmpose_input: 100
    rtmpose_output: 100
    bytetrack_input: 100
    bytetrack_output: 100
    annotation_input1: 100
    annotation_input2: 100

# YOLOX object detection service configuration
yolox:
  enabled: true
  # Model input size [width, height]
  model_input_size: [640, 640]
  # Model URL (will be downloaded automatically)
  model_url: "https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/onnx_sdk/yolox_m_8xb8-300e_humanart-c2c7a14a.zip"
  # Device configuration
  devices: "cuda"
  backend: "onnxruntime"
  # Input configuration
  input:
    type: "rtsp"
    config: "rtsp://localhost:8554,topic=mystream"
  # Output configuration
  output:
    type: "mqtt"
    config: "mqtt://localhost:1883,topic=yolox,qos=2,queue_max_len=50"

# RTMPose pose estimation service configuration
rtmpose:
  enabled: true
  # Model input size [width, height]
  model_input_size: [192, 256]
  # Model URL
  model_url: "https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/onnx_sdk/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.zip"
  # Device configuration
  devices: "cuda"
  backend: "onnxruntime"
  # Input configuration (multi-input)
  input:
    rtsp:
      type: "rtsp"
      config: "rtsp://localhost:8554,topic=mystream"
    mqtt:
      type: "mqtt"
      config: "mqtt://localhost:1883,topic=yolox,qos=2,queue_max_len=100"
  # Output configuration
  output:
    type: "mqtt"
    config: "mqtt://localhost:1883,topic=rtmpose,qos=2,queue_max_len=100"

# ByteTrack object tracking service configuration
bytetrack:
  enabled: true
  # Tracking parameters
  track_thresh: 0.45
  match_thresh: 0.8
  track_buffer: 25
  frame_rate: 30
  per_class: false
  # Device configuration
  devices: "cpu"
  # Input configuration
  input:
    type: "mqtt_sorted"
    config: "mqtt://localhost:1883,topic=yolox,qos=2,buffer_threshold=100"
  # Output configuration
  output:
    type: "mqtt"
    config: "mqtt://localhost:1883,topic=bytetrack,qos=2,queue_max_len=100"

# Annotation visualization service configuration
annotation:
  enabled: true
  # Device configuration
  devices: "cpu"
  # Input configuration (multi-input)
  input:
    rtsp:
      type: "rtsp"
      config: "rtsp://localhost:8554,topic=mystream"
    mqtt1:
      type: "mqtt"
      config: "mqtt://localhost:1883,topic=bytetrack,qos=2,queue_max_len=100"
    mqtt2:
      type: "mqtt"
      config: "mqtt://localhost:1883,topic=rtmpose,qos=2,queue_max_len=100"
  # Output configuration
  output:
    type: "rtsp"
    config: "rtsp://localhost:8554,topic=outstream,width=1920,height=1080,fps=25"

# Service dependencies (startup order)
service_dependencies:
  - name: "yolox"
    depends_on: []
    description: "Object detection service, detects human bounding boxes from RTSP stream"
  - name: "rtmpose"
    depends_on: ["yolox"]
    description: "Pose estimation service, receives detection results for pose estimation"
  - name: "bytetrack"
    depends_on: ["yolox"]
    description: "Object tracking service, tracks detected objects"
  - name: "annotation"
    depends_on: ["rtmpose", "bytetrack"]
    description: "Visualization service, aggregates all results and outputs"

# Monitoring configuration
monitoring:
  # Monitoring interval (seconds)
  interval: 10
  # Monitoring metrics
  metrics:
    - queue_sizes
    - processing_rates
    - memory_usage
    - gpu_usage
  # Alert thresholds
  alerts:
    queue_size_threshold: 1000
    memory_usage_threshold: 0.8
    gpu_memory_threshold: 0.9

# Logging configuration
logging:
  # Log file configuration
  file:
    enabled: true
    path: "logs"
    filename_pattern: "pose_estimation_{timestamp}.log"
    max_size: "100MB"
    backup_count: 10
  # Console output
  console:
    enabled: true
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  # Service-specific logging
  services:
    yolox:
      level: "INFO"
    rtmpose:
      level: "INFO"
    bytetrack:
      level: "INFO"
    annotation:
      level: "INFO" 